### ISSUE TITLE
Cannot testing locally without handling TLS connections

### ISSUE THREAD

**Issue by diemonster** [quintilesims/d.ims.io#33]
By default, `d.ims.io` expects connections to be HTTPS, which is reasonable because docker private repositories _must_ use HTTPS when using Basic Auth:
https://docs.docker.com/registry/insecure/#deploying-a-plain-http-registry

Unfortunately, as a result, our current implementation makes it impossible to test the service locally without standing up a reverse proxy in front of it to terminate SSL. This is because our service doesn't actually handle TLS connections.

**Comment by zpatrick** [comment]
> By default, d.ims.io expects connections to be HTTPS

This is not true. As you noted, the service sits behind a load balancer that terminates SSL before sending it to this service as HTTP. 

More importantly, not being able to test "locally" is a relative issue. 
@tlake and myself are able to handle & test this tool locally because of our development setups. 

For the same reason(s) we don't ship this tool with it's own load balancing and SSL handling mechanisms, it doesn't make much sense to implement them solely for local development.

**Comment by diemonster** [comment]
> More importantly, not being able to test "locally" is a relative issue.
> @tlake and myself are able to handle & test this tool locally because of our development setups.

As long as that's called out in the README re: how to debug and develop this project, I think that's OK.

**Comment by tlake** [comment]
I should probably note that I haven't been able to use Docker on a local instance of d.ims.io; I've been using `curl`s to `localhost:9090`.
